// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ofoq-hero/Current.tsx": () => import("../components/mockups/ofoq-hero/Current.tsx"),
  "./components/mockups/ofoq-hero/ReferenceRedesign.tsx": () => import("../components/mockups/ofoq-hero/ReferenceRedesign.tsx")
};
