// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/FirstLightCyclingLookbook-OVRkX8/ClikClakDuskMix.tsx": () => import("../components/mockups/templates/FirstLightCyclingLookbook-OVRkX8/ClikClakDuskMix.tsx"),
  "./components/mockups/templates/FirstLightCyclingLookbook-icWMNd/ClikClakDuskMix.tsx": () => import("../components/mockups/templates/FirstLightCyclingLookbook-icWMNd/ClikClakDuskMix.tsx"),
  "./components/mockups/templates/WarmLanguageLearningDashboard-CchhSJ/App.tsx": () => import("../components/mockups/templates/WarmLanguageLearningDashboard-CchhSJ/App.tsx")
};
