import type { Lang } from "./extraLangs";

export type UiCopy = {
  header: { clientLogin: string; menu: string; language: string };
  home: {
    badge: string; hero1: string; hero2: string; heroSub: string; request: string; explore: string;
    aboutBadge: string; aboutTitle1: string; aboutTitle2: string; aboutDesc: string; aboutCta: string;
    servicesBadge: string; servicesTitle1: string; servicesTitle2: string; servicesAll: string; more: string;
    whyBadge: string; whyTitle: string; ctaTitle1: string; ctaTitle2: string; ctaDesc: string; contact: string;
    stats: string[]; reasons: { title: string; desc: string }[];
  };
  services: { title: string; badge: string; hero1: string; hero2: string; heroSub: string; view: string; more: string };
  category: { home: string; services: string; badge: string; available: string; service: string; grid: string; list: string; details: string; need: string; needDesc: string; request: string };
  detail: { home: string; services: string; badge: string; request: string; how: string; faq: string; window: string; suitable: string; requirements: string; related: string; details: string };
  auth: {
    clientTitle: string; clientSubtitle: string; login: string; email: string; password: string; forgot: string;
    noAccount: string; create: string; registerTitle: string; registerSubtitle: string; fullName: string;
    phone: string; confirmPassword: string; createAccount: string; haveAccount: string; invalid: string;
    forgotTitle: string; forgotSubtitle: string; checkEmail: string; checkEmailDesc: string; spam: string;
    backLogin: string; sendReset: string; sending: string; resetTitle: string; resetSubtitle: string;
    passwordChanged: string; redirecting: string; goLogin: string; newPassword: string; passwordStrength: string;
    savePassword: string; saving: string; mismatch: string; minPassword: string; invalidReset: string;
  };
  request: {
    title: string; subtitle: string; steps: string[]; company: string; commercialReg: string; activity: string;
    contactEmail: string; contactPhone: string; service: string; package: string; country: string; notes: string;
    chooseService: string; chooseCountry: string; next: string; previous: string; review: string; submit: string;
    success: string; error: string; required: string;
  };
  packages: {
    title: string; badge: string; heroTitle: string; heroHighlight: string; heroSub: string;
    names: string[]; taglines: string[]; badges: string[]; features: string[];
    subscribe: string; compare: string; service: string; silver: string; gold: string; platinum: string;
    help: string; helpTitle: string; contact: string;
  };
  client: {
    portal: string; dashboard: string; requests: string; support: string; logout: string; client: string;
    welcome: string; dashboardSub: string; total: string; active: string; completed: string; newRequests: string;
    newRequest: string; supportAction: string; latest: string; noRequests: string; noRequestsSub: string;
    submitNow: string; requestCount: string; loading: string; requestDetails: string; statusHistory: string;
    messages: string; addNote: string; notePlaceholder: string; noteAdded: string; noteError: string;
    supportSub: string; noMessages: string; noMessagesSub: string; supportPlaceholder: string; sendError: string;
    you: string; invalidRequest: string; backRequests: string; status: Record<string, string>;
    services: Record<string, string>;
  };
  employee: {
    portal: string; login: string; email: string; password: string; emailRequired: string; passwordRequired: string;
    invalid: string; twoFactor: string; code: string; verify: string; verifying: string; back: string;
    barcode: string; logout: string; employee: string; dashboard: string; card: string; profile: string;
    employeePhoto: string;
  };
  adminLogin: {
    title: string; subtitle: string; email: string; password: string; forgot: string; login: string; loggingIn: string;
    emailRequired: string; passwordRequired: string; invalid: string; twoFactor: string; code: string;
    verify: string; verifying: string; back: string; employeeBarcode: string; employeeLogin: string;
  };
  footer: { newsletter: string; newsletterSub: string; email: string; join: string; about: string; services: string; packages: string; contact: string; story: string; vision: string; why: string; formation: string; legal: string; hr: string; government: string; investors: string; silver: string; gold: string; platinum: string; compare: string; form: string; rights: string; privacy: string; terms: string; madeBy: string; location: string; description: string };
};

const en: UiCopy = {
  header: { clientLogin: "Client login", menu: "Menu", language: "Language" },
  home: {
    badge: "OFOQ / SAUDI BUSINESS CONCIERGE", hero1: "We handle", hero2: "the details.", heroSub: "Your trusted partner for HR, government services, visas, and company formation in Saudi Arabia.", request: "Request service", explore: "Explore services",
    aboutBadge: "About OFOQ", aboutTitle1: "Your business partner", aboutTitle2: "in Saudi Arabia", aboutDesc: "We handle government procedures, HR management, and formation requirements — so you can focus entirely on growing your business.", aboutCta: "Learn more",
    servicesBadge: "Our services", servicesTitle1: "Comprehensive", servicesTitle2: "services", servicesAll: "View all services", more: "more services",
    whyBadge: "Why OFOQ?", whyTitle: "We build with you, step by step", ctaTitle1: "Let's boost your", ctaTitle2: "sustainable growth", ctaDesc: "Contact us today and start a real partnership journey.", contact: "Contact us",
    stats: ["Clients served", "Client satisfaction", "Specialists", "Service categories"],
    reasons: [{ title: "Expert team", desc: "Specialists across every area of our services in the Saudi market." }, { title: "Full follow-up", desc: "We follow your file through to closure with regular updates." }, { title: "Digital experience", desc: "A full client portal to track your requests from anywhere." }, { title: "Local expertise", desc: "Deep knowledge of Saudi regulations and government bodies." }],
  },
  services: { title: "Services | OFOQ", badge: "THE OFOQ CATALOG", hero1: "Services designed", hero2: "for your business.", heroSub: "From entity formation to daily operations, we coordinate details through one team and a clear path.", view: "View services", more: "more" },
  category: { home: "Home", services: "Services", badge: "Service category", available: "services available", service: "services", grid: "Grid", list: "List", details: "Details", need: "Need these services?", needDesc: "Contact us and we'll help you identify the right service for your needs.", request: "Request service" },
  detail: { home: "Home", services: "Services", badge: "Service details", request: "Request service", how: "How we work", faq: "Frequently asked questions", window: "Service window", suitable: "Who is it for?", requirements: "Requirements", related: "Other services in this category", details: "Details" },
  auth: { clientTitle: "Client portal", clientSubtitle: "Sign in to follow your requests", login: "Sign in", email: "Email address", password: "Password", forgot: "Forgot password?", noAccount: "Don't have an account?", create: "Create an account", registerTitle: "Create your account", registerSubtitle: "Join the OFOQ client portal", fullName: "Full name", phone: "Phone number", confirmPassword: "Confirm password", createAccount: "Create account", haveAccount: "Already have an account?", invalid: "Invalid email or password", forgotTitle: "Forgot your password?", forgotSubtitle: "Enter your email and we will send a recovery link", checkEmail: "Check your email", checkEmailDesc: "If this email is registered with us, you will receive a reset link within a few minutes.", spam: "Check your spam folder if you do not see it.", backLogin: "Back to sign in", sendReset: "Send recovery link", sending: "Sending...", resetTitle: "Set a new password", resetSubtitle: "Choose a strong password for your account", passwordChanged: "Password changed successfully", redirecting: "You will be redirected to sign in shortly.", goLogin: "Go to sign in now", newPassword: "New password", passwordStrength: "Strength", savePassword: "Save new password", saving: "Saving...", mismatch: "Passwords do not match", minPassword: "Password must be at least 8 characters", invalidReset: "The link is invalid or has expired" },
  request: { title: "New service request", subtitle: "Complete the form and our team will contact you within 24–48 hours", steps: ["Company information", "Contact details", "Service details", "Review"], company: "Company name", commercialReg: "Commercial registration (optional)", activity: "Business activity", contactEmail: "Contact email", contactPhone: "Phone number", service: "Requested service", package: "Package (optional)", country: "Recruitment country (if applicable)", notes: "Additional notes (optional)", chooseService: "Choose a service...", chooseCountry: "Choose a country...", next: "Next", previous: "Previous", review: "Review request", submit: "Submit request", success: "Your request was submitted successfully.", error: "Could not submit the request.", required: "Required" },
  packages: { title: "Packages | OFOQ", badge: "Packages", heroTitle: "Build your", heroHighlight: "success path", heroSub: "Choose the package that fits your business needs.", names: ["Silver package", "Gold package", "Platinum package"], taglines: ["For startups", "Most popular", "For larger organizations"], badges: ["", "Most popular", "Most comprehensive"], features: ["Ministry of Commerce", "Salama platform", "Social insurance", "Medical insurance services", "Zakat and tax services", "Absher and Muqeem platforms", "Consulting services", "Ministry of Media", "Balady platform", "Burden relief service", "Training and development"], subscribe: "Subscribe now", compare: "Compare packages", service: "Service", silver: "Silver", gold: "Gold", platinum: "Platinum", help: "Need help choosing?", helpTitle: "Our team can help", contact: "Contact us" },
  client: { portal: "Client portal", dashboard: "Dashboard", requests: "My requests", support: "Support", logout: "Sign out", client: "Client", welcome: "Welcome", dashboardSub: "Track your requests and contact our team from here.", total: "Total requests", active: "Active requests", completed: "Completed", newRequests: "New requests", newRequest: "New service request", supportAction: "Contact support", latest: "Latest requests", noRequests: "No requests yet", noRequestsSub: "Submit your first request and our team will contact you.", submitNow: "Submit a request now", requestCount: "requests", loading: "Loading...", requestDetails: "Request details", statusHistory: "Status history", messages: "Messages from the OFOQ team", addNote: "Add a note for the team", notePlaceholder: "Write your note here...", noteAdded: "Your note was added", noteError: "Could not send the note", supportSub: "Contact the OFOQ team directly — we reply during business hours.", noMessages: "No messages yet", noMessagesSub: "Send your first message and our team will reply soon.", supportPlaceholder: "Write your message... (Enter to send)", sendError: "Could not send the message", you: "You", invalidRequest: "The request was not found or you do not have access.", backRequests: "Back to requests", status: { new: "New", reviewing: "Under review", approved: "Approved", in_progress: "In progress", completed: "Completed", rejected: "Rejected" }, services: { company_formation: "Company formation", legal_services: "Legal services", trademark: "Trademark registration", government_services: "Government services", hr_management: "Human resources management", gov_platforms: "Government platforms management", investor_services: "Investor services", ipo_preparation: "IPO preparation" } },
  employee: { portal: "Employee portal", login: "Sign in", email: "Email address", password: "Password", emailRequired: "Email is required", passwordRequired: "Password is required", invalid: "Unable to sign in. Check your details and try again.", twoFactor: "Two-factor verification", code: "Verification code", verify: "Confirm", verifying: "Verifying...", back: "Back", barcode: "Sign in with employee barcode", logout: "Sign out", employee: "Employee", dashboard: "Dashboard", card: "My card", profile: "My profile", employeePhoto: "Employee photo" },
  adminLogin: { title: "OFOQ Business Solutions", subtitle: "Sign in to the OFOQ control panel", email: "Email address", password: "Password", forgot: "Forgot password?", login: "Sign in", loggingIn: "Signing in...", emailRequired: "Email is required", passwordRequired: "Password is required", invalid: "Unable to sign in. Check your details and try again.", twoFactor: "Enter your two-factor code", code: "Verification code", verify: "Confirm", verifying: "Verifying...", back: "Back to sign in", employeeBarcode: "Sign in with employee barcode", employeeLogin: "Employee sign in" },
  footer: { newsletter: "Join our newsletter", newsletterSub: "Discover more about our advanced business services", email: "Your email address", join: "Join", about: "About us", services: "Services", packages: "Packages", contact: "Contact", story: "Our story", vision: "Vision & mission", why: "Why OFOQ?", formation: "Company formation", legal: "Legal services", hr: "Human resources", government: "Government platforms", investors: "Investor services", silver: "Silver package", gold: "Gold package", platinum: "Platinum package", compare: "Compare packages", form: "Contact form", rights: "All rights reserved.", privacy: "Privacy policy", terms: "Terms & conditions", madeBy: "Made by", location: "Jeddah — King Abdullah Road", description: "Your trusted business partner in Saudi Arabia — comprehensive services that simplify operations and support sustainable growth." },
};

const ar: UiCopy = {
  ...en,
  header: { clientLogin: "دخول العميل", menu: "القائمة", language: "اللغة" },
  home: { ...en.home, badge: "أفق / شريك الأعمال السعودي", hero1: "نرتّب التفاصيل،", hero2: "لتتفرغ للنمو.", heroSub: "شريكك الموثوق في الموارد البشرية، الخدمات الحكومية، التأشيرات وتأسيس الشركات في المملكة.", request: "اطلب خدمة", explore: "استكشف الخدمات", aboutBadge: "عن أفق", aboutTitle1: "شريك عملك في", aboutTitle2: "المملكة العربية السعودية", aboutDesc: "نحمل عنك الإجراءات الحكومية وإدارة الموارد البشرية ومتطلبات التأسيس — حتى تتفرغ تماماً لنمو أعمالك.", aboutCta: "اعرف المزيد", servicesBadge: "خدماتنا", servicesTitle1: "خدمات متكاملة", servicesTitle2: "وشاملة", servicesAll: "عرض جميع الخدمات", more: "خدمات أخرى", whyBadge: "لماذا أفق؟", whyTitle: "نبني معك خطوة بخطوة", ctaTitle1: "لنعزز نموكم", ctaTitle2: "المستدام", ctaDesc: "تواصل معنا اليوم وابدأ رحلة شراكة حقيقية.", contact: "تواصل معنا", stats: ["عميل تخدمهم أفق", "نسبة رضا العملاء", "خبير متخصص", "تصنيفات خدمية"], reasons: [{ title: "فريق متخصص", desc: "مختصون في كل مجال من مجالات خدماتنا في السوق السعودي." }, { title: "متابعة كاملة", desc: "نتابع ملفك حتى الإغلاق مع تحديثات دورية لك." }, { title: "تجربة رقمية", desc: "بوابة عميل متكاملة لمتابعة طلباتك أينما كنت." }, { title: "خبرة محلية", desc: "نفهم الأنظمة والجهات الحكومية السعودية عن قرب." }] },
  services: { title: "الخدمات | أفق", badge: "دليل خدمات أفق", hero1: "خدمات مصممة", hero2: "لعملك بالكامل.", heroSub: "من تأسيس الكيان إلى تشغيله يومياً، ننسّق التفاصيل عبر فريق واحد ومسار واضح.", view: "عرض الخدمات", more: "خدمات أخرى" },
  category: { home: "الرئيسية", services: "الخدمات", badge: "تصنيف الخدمة", available: "خدمة متاحة", service: "خدمة", grid: "شبكة", list: "قائمة", details: "التفاصيل", need: "هل تحتاج هذه الخدمات؟", needDesc: "تواصل معنا وسنساعدك في تحديد الخدمة المناسبة لاحتياجاتك.", request: "اطلب خدمة" },
  detail: { home: "الرئيسية", services: "الخدمات", badge: "تفاصيل الخدمة", request: "اطلب الخدمة", how: "كيف نعمل", faq: "الأسئلة الشائعة", window: "مدة التنفيذ", suitable: "لمن تناسب؟", requirements: "المتطلبات", related: "خدمات أخرى من نفس التصنيف", details: "التفاصيل" },
  auth: { clientTitle: "بوابة العملاء", clientSubtitle: "سجّل دخولك لمتابعة طلباتك", login: "تسجيل الدخول", email: "البريد الإلكتروني", password: "كلمة المرور", forgot: "نسيت كلمة المرور؟", noAccount: "ليس لديك حساب؟", create: "إنشاء حساب جديد", registerTitle: "إنشاء حساب جديد", registerSubtitle: "انضم لبوابة عملاء أفق", fullName: "الاسم الكامل", phone: "رقم الهاتف", confirmPassword: "تأكيد كلمة المرور", createAccount: "إنشاء الحساب", haveAccount: "لديك حساب بالفعل؟", invalid: "البريد الإلكتروني أو كلمة المرور غير صحيحة", forgotTitle: "نسيت كلمة المرور؟", forgotSubtitle: "أدخل بريدك وسنرسل لك رابط الاسترداد", checkEmail: "تحقق من بريدك الإلكتروني", checkEmailDesc: "إذا كان البريد مسجلاً لدينا، ستصلك رسالة بها رابط إعادة التعيين خلال دقائق.", spam: "تحقق من مجلد Spam إذا لم تجد الرسالة", backLogin: "العودة لتسجيل الدخول", sendReset: "إرسال رابط الاسترداد", sending: "جاري الإرسال...", resetTitle: "تعيين كلمة مرور جديدة", resetSubtitle: "اختر كلمة مرور قوية لحسابك", passwordChanged: "تم تغيير كلمة المرور!", redirecting: "سيتم تحويلك لصفحة الدخول خلال ثوانٍ...", goLogin: "الذهاب لتسجيل الدخول الآن", newPassword: "كلمة المرور الجديدة", passwordStrength: "القوة", savePassword: "حفظ كلمة المرور الجديدة", saving: "جاري الحفظ...", mismatch: "كلمتا المرور غير متطابقتين", minPassword: "كلمة المرور يجب أن تكون 8 أحرف على الأقل", invalidReset: "الرابط غير صالح أو منتهي الصلاحية" },
  request: { title: "طلب خدمة جديد", subtitle: "أكمل النموذج وسيتواصل فريقنا معك خلال 24–48 ساعة", steps: ["معلومات الشركة", "بيانات التواصل", "تفاصيل الخدمة", "المراجعة"], company: "اسم الشركة", commercialReg: "رقم السجل التجاري (اختياري)", activity: "النشاط التجاري", contactEmail: "البريد الإلكتروني للتواصل", contactPhone: "رقم الهاتف", service: "نوع الخدمة المطلوبة", package: "الباقة (اختياري)", country: "دولة الاستقدام (إن انطبق)", notes: "ملاحظات إضافية (اختياري)", chooseService: "اختر الخدمة...", chooseCountry: "اختر الدولة...", next: "التالي", previous: "السابق", review: "مراجعة الطلب", submit: "إرسال الطلب", success: "تم تقديم طلبك بنجاح!", error: "خطأ في إرسال الطلب", required: "مطلوب" },
  packages: { ...en.packages, title: "الباقات | أفق", badge: "الباقات", heroTitle: "اصنع مسار", heroHighlight: "نجاحك", heroSub: "اختر الباقة التي تناسب احتياجات عملك", names: ["الباقة الفضية", "الباقة الذهبية", "الباقة البلاتينية"], taglines: ["للشركات الناشئة", "الأكثر طلباً", "للمؤسسات الكبرى"], badges: ["", "الأكثر طلباً", "الأشمل"], features: ["وزارة التجارة", "منصة سلامة", "التأمينات الاجتماعية", "خدمات التأمين الطبي", "خدمات الزكاة والضريبة", "منصة أبشر ومقيم", "خدمات الاستشارات", "وزارة الإعلام", "منصة بلدي", "خدمة تخفيف الأعباء", "التدريب والتطوير"], subscribe: "اشترك الآن", compare: "مقارنة الباقات", service: "الخدمة", silver: "فضية", gold: "ذهبية", platinum: "بلاتينية", help: "هل تحتاج إلى مساعدة في الاختيار؟", helpTitle: "فريقنا يساعدك", contact: "تواصل معنا" },
  client: { ...en.client, portal: "بوابة العملاء", dashboard: "الرئيسية", requests: "طلباتي", support: "الدعم", logout: "تسجيل الخروج", client: "العميل", welcome: "أهلاً", dashboardSub: "تابع طلباتك وتواصل مع فريقنا من هنا", total: "إجمالي الطلبات", active: "طلبات نشطة", completed: "مُنجزة", newRequests: "طلبات جديدة", newRequest: "طلب خدمة جديد", supportAction: "تواصل مع الدعم", latest: "آخر الطلبات", noRequests: "لا توجد طلبات بعد", noRequestsSub: "ابدأ بتقديم طلبك الأول وسيتواصل فريقنا معك", submitNow: "تقديم طلب الآن", requestCount: "طلب", loading: "جارٍ التحميل...", requestDetails: "تفاصيل الطلب", statusHistory: "سجل الحالات", messages: "رسائل من فريق أفق", addNote: "إضافة ملاحظة للفريق", notePlaceholder: "اكتب ملاحظتك هنا...", noteAdded: "تمت إضافة ملاحظتك", noteError: "خطأ في إرسال الملاحظة", supportSub: "تواصل مباشرة مع فريق أفق — نرد خلال أوقات الدوام", noMessages: "لا توجد رسائل بعد", noMessagesSub: "أرسل رسالتك الأولى وسيرد عليك فريقنا قريباً", supportPlaceholder: "اكتب رسالتك... (Enter للإرسال)", sendError: "خطأ في إرسال الرسالة", you: "أنت", invalidRequest: "الطلب غير موجود أو غير مصرح لك", backRequests: "العودة للطلبات", status: { new: "جديد", reviewing: "قيد المراجعة", approved: "موافق عليه", in_progress: "قيد التنفيذ", completed: "مُنجز", rejected: "مرفوض" }, services: { company_formation: "تأسيس الشركات", legal_services: "الخدمات القانونية", trademark: "تسجيل العلامات التجارية", government_services: "الخدمات الحكومية", hr_management: "إدارة الموارد البشرية", gov_platforms: "إدارة المنصات الحكومية", investor_services: "خدمات المستثمرين", ipo_preparation: "تأهيل للإدراج" } },
  employee: { ...en.employee, portal: "بوابة الموظفين", login: "تسجيل الدخول", email: "البريد الإلكتروني", password: "كلمة المرور", emailRequired: "البريد مطلوب", passwordRequired: "كلمة المرور مطلوبة", invalid: "تعذر تسجيل الدخول. تحقق من البيانات وحاول مرة أخرى.", twoFactor: "التحقق الثنائي", code: "رمز التحقق", verify: "تأكيد", verifying: "جارٍ التحقق...", back: "رجوع", barcode: "تسجيل الدخول بباركود الموظف", logout: "تسجيل الخروج", employee: "موظف", dashboard: "لوحتي", card: "بطاقتي", profile: "ملفي", employeePhoto: "صورة الموظف" },
  adminLogin: { ...en.adminLogin, title: "أفق لحلول الأعمال", subtitle: "سجّل دخولك إلى لوحة تحكم أفق", email: "البريد الإلكتروني", password: "كلمة المرور", forgot: "نسيت كلمة المرور؟", login: "تسجيل الدخول", loggingIn: "جارٍ تسجيل الدخول...", emailRequired: "البريد الإلكتروني مطلوب", passwordRequired: "كلمة المرور مطلوبة", invalid: "تعذر تسجيل الدخول. تحقق من البيانات وحاول مرة أخرى.", twoFactor: "أدخل رمز التحقق الثنائي", code: "رمز التحقق", verify: "تأكيد", verifying: "جارٍ التحقق...", back: "العودة لتسجيل الدخول", employeeBarcode: "تسجيل الدخول بباركود الموظف", employeeLogin: "تسجيل دخول الموظف" },
  footer: { ...en.footer, newsletter: "للتسجيل في نشرتنا", newsletterSub: "لمعرفة المزيد حول خدمات الأعمال المتقدمة", email: "بريدك الإلكتروني", join: "انضم", about: "من نحن", services: "الخدمات", packages: "الباقات", contact: "التواصل", story: "قصتنا", vision: "رؤيتنا ومهمتنا", why: "لماذا أفق؟", formation: "تأسيس الشركات", legal: "الخدمات القانونية", hr: "الموارد البشرية", government: "المنصات الحكومية", investors: "خدمات المستثمرين", silver: "الباقة الفضية", gold: "الباقة الذهبية", platinum: "الباقة البلاتينية", compare: "مقارنة الباقات", form: "نموذج التواصل", rights: "جميع الحقوق محفوظة.", privacy: "سياسة الخصوصية", terms: "الشروط والأحكام", madeBy: "صُنع بواسطة", location: "جدة — طريق الملك عبدالله", description: "شريكك الموثوق لأعمالك في السعودية — نقدم حلولاً شاملة لتسهيل أعمالك ودعم نموك المستدام." },
};

type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends Array<any> ? T[K] : T[K] extends object ? DeepPartial<T[K]> : T[K];
};

const overrides: Record<Exclude<Lang, "ar" | "en">, DeepPartial<UiCopy>> = {
  ur: { header: { clientLogin: "کلائنٹ لاگ اِن", menu: "مینو", language: "زبان" }, home: { ...en.home, hero1: "ہم سنبھالتے ہیں", hero2: "آپ کی تفصیلات۔", heroSub: "سعودی عرب میں انسانی وسائل، سرکاری خدمات، ویزوں اور کمپنی بنانے کے لیے آپ کا قابل اعتماد ساتھی۔", request: "خدمت کی درخواست", explore: "خدمات دیکھیں" }, services: { ...en.services, title: "خدمات | OFOQ", hero1: "آپ کے کاروبار", hero2: "کے لیے خدمات۔" }, category: { ...en.category, home: "ہوم", services: "خدمات", request: "خدمت کی درخواست", details: "تفصیلات" }, detail: { ...en.detail, home: "ہوم", services: "خدمات", request: "خدمت طلب کریں", how: "ہم کیسے کام کرتے ہیں", faq: "اکثر پوچھے گئے سوالات" }, auth: { ...en.auth, clientTitle: "کلائنٹ پورٹل", clientSubtitle: "اپنی درخواستیں دیکھنے کے لیے لاگ اِن کریں", login: "لاگ اِن", email: "ای میل", password: "پاس ورڈ", create: "نیا اکاؤنٹ بنائیں" }, request: { ...en.request, title: "نئی خدمت کی درخواست", steps: ["کمپنی کی معلومات", "رابطے کی معلومات", "خدمت کی تفصیلات", "جائزہ"], next: "اگلا", previous: "پچھلا", submit: "درخواست بھیجیں" } },
  hi: { header: { clientLogin: "क्लाइंट लॉगिन", menu: "मेन्यू", language: "भाषा" }, home: { ...en.home, hero1: "हम संभालते हैं", hero2: "आपका काम।", heroSub: "सऊदी अरब में HR, सरकारी सेवाओं, वीज़ा और कंपनी गठन के लिए आपका विश्वसनीय साथी।", request: "सेवा का अनुरोध", explore: "सेवाएँ देखें" }, services: { ...en.services, title: "सेवाएँ | OFOQ", hero1: "आपके व्यवसाय", hero2: "के लिए सेवाएँ।" }, category: { ...en.category, home: "होम", services: "सेवाएँ", request: "सेवा का अनुरोध", details: "विवरण" }, detail: { ...en.detail, home: "होम", services: "सेवाएँ", request: "सेवा का अनुरोध", how: "हम कैसे काम करते हैं" }, auth: { ...en.auth, clientTitle: "क्लाइंट पोर्टल", clientSubtitle: "अपने अनुरोधों को देखने के लिए लॉग इन करें", login: "लॉग इन", create: "नया खाता बनाएँ" }, request: { ...en.request, title: "नई सेवा का अनुरोध", steps: ["कंपनी की जानकारी", "संपर्क विवरण", "सेवा विवरण", "समीक्षा"], next: "अगला", previous: "पिछला", submit: "अनुरोध भेजें" } },
  id: { header: { clientLogin: "Login klien", menu: "Menu", language: "Bahasa" }, home: { ...en.home, hero1: "Kami menangani", hero2: "detail bisnis Anda.", heroSub: "Mitra tepercaya untuk HR, layanan pemerintah, visa, dan pendirian perusahaan di Arab Saudi.", request: "Ajukan layanan", explore: "Jelajahi layanan" }, services: { ...en.services, title: "Layanan | OFOQ", hero1: "Layanan untuk", hero2: "bisnis Anda." }, category: { ...en.category, home: "Beranda", services: "Layanan", request: "Ajukan layanan", details: "Detail" }, detail: { ...en.detail, home: "Beranda", services: "Layanan", request: "Ajukan layanan", how: "Cara kerja kami" }, auth: { ...en.auth, clientTitle: "Portal klien", clientSubtitle: "Masuk untuk melihat permintaan Anda", login: "Masuk", create: "Buat akun" }, request: { ...en.request, title: "Permintaan layanan baru", steps: ["Informasi perusahaan", "Detail kontak", "Detail layanan", "Tinjauan"], next: "Berikutnya", previous: "Sebelumnya", submit: "Kirim permintaan" } },
  de: { header: { clientLogin: "Kundenlogin", menu: "Menü", language: "Sprache" }, home: { ...en.home, hero1: "Wir kümmern uns", hero2: "um die Details.", heroSub: "Ihr zuverlässiger Partner für HR, Behördendienste, Visa und Firmengründung in Saudi-Arabien.", request: "Service anfragen", explore: "Leistungen entdecken" }, services: { ...en.services, title: "Leistungen | OFOQ", hero1: "Leistungen für", hero2: "Ihr Unternehmen." }, category: { ...en.category, home: "Startseite", services: "Leistungen", request: "Service anfragen", details: "Details" }, detail: { ...en.detail, home: "Startseite", services: "Leistungen", request: "Service anfragen", how: "So arbeiten wir" }, auth: { ...en.auth, clientTitle: "Kundenportal", clientSubtitle: "Melden Sie sich an, um Anfragen zu verfolgen", login: "Anmelden", create: "Konto erstellen" }, request: { ...en.request, title: "Neue Serviceanfrage", steps: ["Unternehmensdaten", "Kontaktdaten", "Servicedetails", "Prüfung"], next: "Weiter", previous: "Zurück", submit: "Anfrage senden" } },
  es: { header: { clientLogin: "Acceso de clientes", menu: "Menú", language: "Idioma" }, home: { ...en.home, hero1: "Nos ocupamos", hero2: "de los detalles.", heroSub: "Su socio de confianza para RR. HH., servicios públicos, visados y constitución de empresas en Arabia Saudí.", request: "Solicitar servicio", explore: "Explorar servicios" }, services: { ...en.services, title: "Servicios | OFOQ", hero1: "Servicios para", hero2: "su empresa." }, category: { ...en.category, home: "Inicio", services: "Servicios", request: "Solicitar servicio", details: "Detalles" }, detail: { ...en.detail, home: "Inicio", services: "Servicios", request: "Solicitar servicio", how: "Cómo trabajamos" }, auth: { ...en.auth, clientTitle: "Portal de clientes", clientSubtitle: "Inicie sesión para seguir sus solicitudes", login: "Iniciar sesión", create: "Crear una cuenta" }, request: { ...en.request, title: "Nueva solicitud de servicio", steps: ["Información de la empresa", "Datos de contacto", "Detalles del servicio", "Revisión"], next: "Siguiente", previous: "Anterior", submit: "Enviar solicitud" } },
};

export function getUiCopy(lang: Lang): UiCopy {
  if (lang === "ar") return ar;
  if (lang === "en") return en;
  const patch = overrides[lang] || {};
  const merge = (base: any, next: any): any => {
    if (!next || typeof next !== "object" || Array.isArray(next)) return next ?? base;
    const output = { ...base };
    for (const key of Object.keys(next)) output[key] = merge(base?.[key], next[key]);
    return output;
  };
  return merge(en, patch) as UiCopy;
}